apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stress
  name: stress
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: stress
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stress
    spec:
      containers:
      - env:
        - name: STRESS_VM
          value: "10"
        - name: STRESS_VM_BYTES
          value: "256"
        image: mtr.external.otc.telekomcloud.com/eumel8/stress:latest
        imagePullPolicy: Always
        name: stress
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: stress
      serviceAccountName: stress
